#!/bin/sh
cd "$(dirname "$0")"

python generate.py

echo "Serving at http://localhost:9001"
if [ -n "$1" ]; then
    echo "View post at http://localhost:9001/posts/$1.html"
fi
python -m http.server 9001